content_view:
#project template override

- contenttype: folder
  viewmode: full
  id: 3
  to: folder/frontpage.html

- contenttype: folder
  viewmode: full
  field_display_type: news
  to: folder/news.html

- contenttype: article
  viewmode: full
  to: article/full.html

- contenttype: folder
  viewmode: full
  to: folder/full.html  
