##General settings
general:
  var_folder: "/Users/xc/dev/dmtest/var"
  upload_tempfolder: "upload_temp"
  send_from: "noreply@test.no"
  host: "127.0.0.1:9200"
  image_thumbnail_size: "600x400"
  image_thumbnail_folder: "images/thumbnail"
  template_folder: "web/templates"

database:
   type: mysql
   host: 127.0.0.1
   username: dmdemo
   password: dmdemo
   database: dmdemo

#todo: use path
sites:
  - identifier: dmdemo
    host: "localhost:9200"
    #path: "demo"
    root: 3
    default: 3
    template_folder:
      - "demo"  #first template folder will be used for base template(layout)
      - "test" # todo: idea to support package like "<packagename>, test"
  - identifier: site2
    host: "localhost:9201"
    path: "site2"
    root: 3
    default: 3
    template_folder:
      - "site2"  #first template folder will be used for base template(layout)
      - "test" # todo: idea to support package like "<packagename>, test"

rest_list_fields:
   report: ["cid", "version", "published", "modified", "author", "author_name", "cuid", "status"]

#permission related
permission:
  rest_allowed_operations: ["eui/all"]

auth:
   refresh_token_secret_key: "1223123dfsldsfbsdfbsfsf-fdsfdsfl"
   refresh_token_expiry: 180
   access_token_secret_key: "fsfsfsf333333sdf555456"
   access_token_expiry: 50

internal:
  location_columns: ["id", "parent_id", "main_id","hierarchy", "depth", "content_type","content_id", "language","identifier_path", "name", "is_hidden", "is_invisible","priority", "uid", "section", "p"]
