##General settings
general:
  var_folder: "var" # support absoluate or relative under dmapp
  upload_tempfolder: "upload_temp" #temporary folder for file upload. under var_folder
  var_baseurl: "/var/" #used to wash image in richtext only

  #mail related
  mail_host: "127.0.0.1:25" #office365: smtp.office365.com:587
  send_from: "noreply@test.com"  #send from
  mail_password: "" # empty if sent from local server

  #listen   
  host: "127.0.0.1:9200" #serve host

  #image
  image_thumbnail_size: "600x400" 
  image_thumbnail_folder: "images/thumbnail" #thumbnail under var_folder
  
  #template
  template_folder: "web/templates" #template folder for website

  #debug
  debug_header: "DMDebug" #putting this to header with debug token will enable debug for this request
  debug_token_last: "10m" #debug token's lasting time.

database:
   type: mysql
   host: "127.0.0.1"
   username: "dmdemo"
   password: "dmdemo"
   database: "dmdemo"

graphql:
  api_key: "dddd7383423424sjfshfgfysifsik"

user:
  unique_email: true

site_settings:
  site_user: 2 ##web site user when visiting

#todo: use path
sites:
  - identifier: dmdemo
    host: "localhost:9200"
    #path: "demo"
    root: 3
    default: 3
  - identifier: site2
    host: "localhost:9201"
    path: "site2"
    root: 3
    default: 3

rest:
  upload_file_auth: false #auth upload file or not

rest_list_fields:
   report: ["cid", "version", "published", "modified", "author", "author_name", "cuid", "status"]

#permission related
permission:
  rest_allowed_operations: ["eui/all"]

auth:
   rememberme_token_expiry: 30 #days
   rememberme_enabled: false
   refresh_token_secret_key: "1223123dfsldsfbsdfbsfsf-fdsfdsfl"
   refresh_token_expiry: "3h"
   access_token_secret_key: "fsfsfsf333333sdf555456"
   access_token_expiry: "30m"
