##include template override rule files. 
##Note: position of "include" doesn't matter, the system will proceed included file first.
include:
    - site: dmdemo
      template_folder: "sites/demo" # will use template under template_folder unless it starts from ~/
      file: "override_sites/dmdemo" # don't include file suffix since it support yaml, json

content_view:
#project template override

# default template override
- viewmode: block
  to: viewmode/block.html

# Note: it will be useful to have this
#- to: default.html

field:
#available keys for field override: fieldtype, field, contenttype, site
- to: fieldtype/{fieldtype}.html