##include template override rule files. 
##Note: position of "include" doesn't matter, the system will proceed included file first.
include:
    - site: dmdemo
      file: "override_sites/dmdemo" # don't include file format since it support yaml, json

content_view:
#project template override
- contenttype: folder
  viewmode: full
  to: folder/full.html

# default template override
- contenttype: article
  viewmode: full
  to: article/full.html

- viewmode: article
  viewmode: block
  to: article/block.html

- viewmode: block
  to: block.html

field:
#available keys for field override: fieldtype, field, contenttype, site
- to: fieldtype/{fieldtype}.html